services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: build
      args:
        PORT: ${PORT:-3131}
    command: ./server
    volumes:
      - ./src:/app/src
    networks:
      app_network:
        aliases:
          - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT:-3131}:${PORT:-3131}"
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
      - docker/app/.env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3131}/healthz"]
      interval: 600s
      timeout: 300s
      retries: 1
      start_period: 90s

  postgres:
    build:
      context: docker/postgres
    hostname: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - docker/postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kafka:
    build:
      context: docker/kafka
    hostname: kafka
    ports:
      - "9094:9094"
    env_file:
      - docker/kafka/.env
    networks:
      - app_network
    restart: unless-stopped

  redis:
    build:
      context: docker/redis
    hostname: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    env_file:
      - docker/redis/.env
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli --user $$REDIS_USERNAME -a $$REDIS_PASSWORD ping | grep -q PONG",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  otel:
    build:
      context: docker/otel
    ports:
      - "4318:4318"
    env_file:
      - docker/otel/.env
    networks:
      - app_network
    restart: unless-stopped

  spotlight:
    build:
      context: docker/spotlight
    ports:
      - "8969:8969"
    env_file:
      - docker/spotlight/.env
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
