services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: build
      args:
        PORT: ${PORT:-3131}
    command: /app/server
    volumes:
      - ./src:/app/src
    networks:
      app_network:
        aliases:
          - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT:-3131}:${PORT:-3131}"
    restart: unless-stopped
    env_file:
      - .env
      - docker/app/.env
    depends_on:
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthz"]
      interval: 600s
      timeout: 300s
      retries: 1
      start_period: 40s

  kafka:
    build:
      context: docker/kafka
    hostname: kafka
    ports:
      - "9094:9094"
    env_file:
      - docker/kafka/.env
    networks:
      - app_network
    restart: unless-stopped

  otel:
    build:
      context: docker/otel
    ports:
      - "4318:4318"
    env_file:
      - docker/otel/.env
    networks:
      - app_network
    restart: unless-stopped

  spotlight:
    build:
      context: docker/spotlight
    ports:
      - "8969:8969"
    env_file:
      - docker/spotlight/.env
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
