import path from "path";

const modulesDir = path.join(import.meta.dir, "../src/modules");
const glob = new Bun.Glob("*/routes.ts");
const files = [...glob.scanSync(modulesDir)]
  .map((file) => file.replaceAll("\\", "/"))
  .sort();

const imports = files
  .map((file, index) => {
    const modulePath = `./${file.replace(/\.ts$/, "")}`;
    return `import * as route${index} from "${modulePath}";`;
  })
  .join("\n");

const registry = files.map((_, index) => `route${index}`).join(", ");

const content = `// Auto-generated by scripts/generate-route-registry.ts — do not edit
${imports}

export const routeModules = [${registry}];
`;

await Bun.write(path.join(modulesDir, "routes.registry.ts"), content);
console.log(`Generated routes.registry.ts (${files.length} modules)`);
